name: RSpec Tests

on:
  push:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.4', '3.3', '3.2']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        # Using this SHA fixes https://github.com/ruby/setup-ruby/issues/595
        uses: ruby/setup-ruby@086ffb1a2090c870a3f881cc91ea83aa4243d408 # v1.195.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Installing all gem versions via Appraisal
        run: bundle exec appraisal install
      - name: Create tmp directory
        run: mkdir -p ~/tmp/rspec
      - name: Run tests
        run: bundle exec appraisal rspec --format progress --format RspecJunitFormatter --out ~/tmp/rspec/rspec.xml
      - name: Push to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
